card_image: ''
created_at: 2025-02-19 19:55:35.212000
creator_id: unknown
deployment:
  last_deployed: null
  type: null
  url: ''
description: Visualize 3D STL and 3MF mesh objects using Python and Streamlit
domain: ''
features:
- ''
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: null
  remote: null
  url: https://github.com/memextech/3d_mesh_viewer
hero_image: ''
icon: ''
is_published: true
pills:
- icon: ''
  label: ''
  prompt: ''
project_id: tCPMOlPrr0hQ1TRklsWS
published_at: 2025-02-19 19:55:57.760000
requirements:
- description: ''
  type: ''
slug: 3d-mesh-viewer
storage:
  compression_enabled: null
  gcs_path: null
  last_sync: null
  max_file_size_mb: null
  size_bytes: null
title: 3D Mesh Viewer
tools:
- name: ''
  role: ''
  type: ''
  version: ''
updated_at: 2025-02-19 19:55:57.760000
